name: test
on: [push , workflow_dispatch]
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: create repo
            uses: actions/checkout@v5
           
          - name: install packages
            run: npm ci

          - name: run test
            run: npm run test
          