name: github actions
on: [push , workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: create repo
            uses: actions/checkout@v5
           
          - name: install packages
            run: npm ci

          - name: run test
            run: npm run test
    

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: create repo
            uses: actions/checkout@v5
           
          - name: install packages
            run: npm ci

          - name: run test
            run: npm run test

          - name: make build
            run: npm run build
          
          - name: make build file
            uses: actions/upload-artifact@v4
            with:
              name: dist
              path: .next
    
 
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: create repo
            uses: actions/checkout@v5
           
          - name: install packages
            run: npm ci

          - name: download dist files
            uses: actions/download-artifact@v4
            with:
              name: dist
              path: .next
          - name: deploy
            run: echo "deployment"